### ISSUE TITLE
Add a Contributing Guidelines and CODE_OF_CONDUCT file to the repository

### ISSUE THREAD

**Issue by Rutam21** [amplication/site#146]
## Introduction
Amplication Site currently doesn't have Contributing Guidelines and CODE_OF_CONDUCT files. The task is to create these two files for this repository as per the files in Amplication repository. 

## Tasks summary:
 - [ ] Fork & clone this repository
 - [ ] Prepare Contributing Guidelines file in CONTRIBUTING.md
 - [ ] Prepare CODE_OF_CONDUCT file in CODE_OF_CONDUCT.md
 - [ ] Push changes to master and test issue forms on your fork
 - [ ] Submit pull request

**Comment by Rutam21** [comment]
@yuval-hazaz Please have a look and give me a heads up so that I can go ahead and raise a PR to resolve this issue. Thanks.
